## OP4 Demo

The Jupyter notebook for this demo can be found in:
   - docs/quick_start/demo/op4_demo.ipynb
   - https://github.com/SteveDoyle2/pyNastran/tree/master/docs/quick_start/demo/op4_demo.ipynb

The OP4 is a Nastran input/output format that can store matrices.

The OP2 can as well, but is less validated in regards to matrices.

#### Import pyNastran

In [1]:
import os

import pyNastran
pkg_path = pyNastran.__path__[0]
pkg_path = r'C:\Users\sdoyle\Desktop\demo\pyNastran\pyNastran'

from pyNastran.utils import print_bad_path
from pyNastran.op4.op4 import read_op4
import numpy as np
#from numpy import float32, float64, int32, int64, product

# decrease output precision
np.set_printoptions(precision=3, threshold=20)

#### Print the docstring


In [2]:
help(read_op4)

Help on function read_op4 in module pyNastran.op4.op4:

read_op4(op4_filename: Union[str, pathlib.PurePath, NoneType] = None, matrix_names: Optional[list] = None, precision: str = 'default', debug: bool = False, log=None) -> dict
    Reads a NASTRAN OUTPUT4 file, and stores the
    matrices as the output arguments.  The number of
    matrices read is defined by the list matrix_names.  By default, all
    matrices will be read.  The resulting output is a dictionary of
    matrices that are accessed by their name.
    
    .. code-block:: python
    
       >>> from pyNastran.op4.op4 import OP4
       >>> op4 = OP4()
    
       # get all the matrices
       >>> matrices = op4.read_op4(op4_filename)
       >>> MatrixA = matrices['A']
       >>> MatrixB = matrices['B']
       >>> MatrixC = matrices['C']
    
       # or to reduce memory usage
       >>> matrices = op4.read_op4(op4_filename, matrix_names=['A', 'B'])
       >>> MatrixA = matrices['A']
       >>> MatrixB = matrices['B']
    

### So as you can see, Nastran has many matrix formats.

In [ ]:
# read the op4, will pop open a dialog box
matrices = read_op4()

In [3]:
op4_filename = os.path.join(pkg_path, '..', 'models', 'iSat', 'ISat_Launch_Sm_4pt.op4')
assert os.path.exists(op4_filename), print_bad_path(op4_filename)

#specify the file
matrices = read_op4(op4_filename)

### There are more ways to read an OP4

In [4]:
# only 1 matrix
matrices = read_op4(op4_filename, matrix_names='FLAMA', debug=False)

# 1 or more matrices
matrices = read_op4(op4_filename, matrix_names=['FLAMA','UGEXT'])

In [5]:
# extract a matrix
from pyNastran.utils import print_bad_path, object_stats
flama = matrices['FLAMA']
print(f'{flama}\n')
print(object_stats(flama))


Matrix['FLAMA'];    shape=(3, 167);   type=numpy.ndarray;                    dtype=float32;   desc=rectangular

Matrix:
  Complex : array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
  GCi    : array([0, 0, 0, ..., 2, 2, 2], dtype=int64)
  GCi_GCj : (array([0, 0, 0, ..., 2, 2, 2], dtype=int64), array([  0,   1,   2, ..., 164, 165, 166], dtype=int64))
  GCj    : array([  0,   1,   2, ..., 164, 165, 166], dtype=int64)
  Real   : array([ 8.358,  9.507, 15.664, ...,  1.   ,  1.   ,  1.   ], dtype=float32)
  col_dof : None
  col_nid : None
  data   : array([[  8.358,   9.507,  15.664, ..., 395.101, 395.329, 397.237],
       [  0.   ,   0.   ,   0.   , ...,   0.   ,   0.   ,   0.   ],
       [  1.   ,   1.   ,   1.   , ...,   1.   ,   1.   ,   1.   ]],
      dtype=float32)
  dtype_str : 'float32'
  form   : 2
  is_complex : False
  is_dense : True
  is_matpool : False
  is_real : True
  is_sparse : False
  name   : 'FLAMA'
  row_dof : None
  row_nid : None
  shape  : (3, 167)
  shape_str : 

In [6]:
print("keys = %s" % matrices.keys())

keys = dict_keys(['FLAMA', 'UGEXT'])


In [7]:
print(list(matrices.keys()))
flama = matrices['FLAMA']
print('flama:')
print("  form = %s" % (flama.form))
print("  type = %s" % type(flama.data[0,0]))
print("  nvals = %s\n" % flama.data.size)

ugext = matrices['UGEXT']
print('ugext:')
print("  form = %s" % (ugext.form))
print("  type = %s" % type(ugext.data[0,0]))
print("  shape = %s" % str(ugext.data.shape))
print("  nvals = %s" % ugext.data.size)

['FLAMA', 'UGEXT']
flama:
  form = 2
  type = <class 'numpy.float32'>
  nvals = 501

ugext:
  form = 2
  type = <class 'numpy.float64'>
  shape = (32274, 167)
  nvals = 5389758


In [8]:
print(ugext.data[:,:])
print(ugext.data.shape)
#print(flama)

[[ 5.548e-03  4.669e-06  1.816e-04 ...  1.038e-01  6.898e-02  1.901e-02]
 [-2.133e-04  5.699e-03 -2.393e-02 ...  1.038e-02 -5.254e-02 -1.187e-01]
 [ 8.469e-04  1.512e-03 -7.038e-03 ... -2.629e-01 -2.135e-01  1.474e-01]
 ...
 [-3.006e-07  5.476e-05 -6.343e-04 ...  8.170e-03 -2.790e-02  2.645e-02]
 [-1.723e-06  1.278e-06  1.805e-06 ... -4.877e-03 -4.630e-03 -6.870e-03]
 [ 7.271e-06  3.394e-06  2.716e-06 ... -7.789e-03 -7.146e-03 -8.940e-03]]
(32274, 167)
